apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-pagamento-deployment
  labels:
    app: fiap-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-pagamento
  template:
    metadata:
      labels:
        app: fiap-pagamento
    spec:
      containers:
        - name: fiap-pagamento
          image: 841162698708.dkr.ecr.us-east-1.amazonaws.com/ms-payment:${GITHUB_SHA}
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "us-east-1"
            - name: DYNAMODB_TABLE_NAME
              value: "payments-table"
            - name: AWS_SQS_QUEUE_ORDER
              value: "https://sqs.us-east-1.amazonaws.com/841162698708/order-queue"
            - name: AWS_SQS_QUEUE_PAYMENT
              value: "https://sqs.us-east-1.amazonaws.com/841162698708/payment-queue"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
